Add files via upload
german-leontiev/python_hometasks pull request #15
Opened 2024-11-27 07:33 UTC by Solt3ro

![meme-kl](https://github.com/user-attachments/assets/3e1421ec-1a31-41e2-9dd2-71281e75f22c)
9,10,6 таски не смог,хотя в 10 тот же "шифр Цезаря" вроде как

2024-11-30 21:29 UTC, german-leontiev requested changes

2024-12-04 15:07 UTC, Solt3ro commented on Module -19(string)/Task_9.py
Этот таск я не смог сделать,поэтому оставил как есть и забил

2024-12-10 13:34 UTC, german-leontiev requested changes

2024-12-10 13:34 UTC, german-leontiev commented on Module -19(string)/Task_9.py
> +text_2 = ' '.join(i[::-1] for i in text.split())
In [2]: ' '.join(i[::-1] for i in a.split())
Out[2]: 'ятоХ ., онжо:мзов и .тен'

А надо так:
Сообщение: Хотя ,. возм:ожно и нет.
Новое сообщение: ятоХ ,. мзов:онжо и тен.

2024-12-10 22:27 UTC, merged