Module 22(recurs)
german-leontiev/python_hometasks pull request #19
Opened 2024-12-09 18:42 UTC by Solt3ro

![e50ba3b05e27587b94c35cbb8a612ca2](https://github.com/user-attachments/assets/6e77e3c4-fa33-4905-96c6-8f6d81280855)

2024-12-16 16:35 UTC, german-leontiev requested changes
Проверь 1 и 7

2024-12-16 16:35 UTC, german-leontiev commented on Module 22(recurs)/task_1.py
Во-первых не выводит само максимальное число, а во вторых выводит в обратном порядке
```
(base) ➜  Module 22(recurs) git:(Module-22(recurs)) python task_1.py
Введите num: 1
Введите num: 20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
```

2024-12-16 16:35 UTC, german-leontiev commented on Module 22(recurs)/task_7.py
> +            result.extend(num(i))
```
Traceback (most recent call last):
  File "/home/german/python_hometasks/Module 22(recurs)/task_7.py", line 35, in <module>
    print(main(primer))
          ^^^^^^^^^^^^
  File "/home/german/python_hometasks/Module 22(recurs)/task_7.py", line 26, in main
    result.extend(num(i))
                  ^^^^^^
TypeError: 'list' object is not callable
```

2024-12-16 16:35 UTC, german-leontiev commented on Module 22(recurs)/task_7.py
Программа падает

2024-12-19 18:11 UTC, Solt3ro commented on Module 22(recurs)/task_1.py
А я не помню уже,но там 2! функции) и первая збс работает

2024-12-20 11:02 UTC, german-leontiev approved these changes

2024-12-20 11:02 UTC, merged