Module-26(OOP2)
german-leontiev/python_hometasks pull request #23
Opened 2024-12-19 18:05 UTC by Solt3ro

Там чет последние 3 таска сложна,хз
![cover](https://github.com/user-attachments/assets/669352d4-b776-484f-866a-6442a9315eb9)

2024-12-20 11:17 UTC, german-leontiev requested changes
Нужны правки в задачах 2, 3

2024-12-20 11:17 UTC, german-leontiev commented on Module-26(OOP2)/task_2.py
Ошибка в следующем:
1. Метод `one_day` записывает сообщение в лог, но возвращает `False`, не выбрасывая исключение. При этом исключения `KillError`, `DrunkError` и другие объявлены, но ни разу не используются по назначению.
2. В строке `super().get(key, default)` в классе `MyDict` результат выполнения метода `super()` никак не используется, и по сути этот вызов ничего не делает.

2024-12-20 11:17 UTC, german-leontiev commented on Module-26(OOP2)/task_3.py
Ошибка в строке:
```python
super().get(key, default)
```
Эта строка не делает ничего полезного, так как результат вызова `super().get` не используется. Основная ошибка:
- Метод `get` не работает так, как описано в задаче: он по-прежнему возвращает `None`, если ключа нет.

2024-12-20 23:21 UTC, Solt3ro commented on Module-26(OOP2)/task_3.py
Он же 0 возвращает,а строку просто забыл убрать

2024-12-21 09:46 UTC, german-leontiev approved these changes

2024-12-21 09:46 UTC, merged